# Generated by Django 2.1.7 on 2019-03-04 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_list_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='created_on',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
