# Generated by Django 2.1.7 on 2019-03-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_list_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
