# Generated by Django 2.1.7 on 2019-03-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20190304_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
